config/routes.rb
Tourrest::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root to: 'welcome#index'

  scope controller: :pages do
    get 'service/:page_code', to: :service_page,  as: :service_page, constraints: { page_code: /#{Settings.service_pages.join('|')}/ }
    get '/:page_code', to: :simple_page,  as: :simple_page, constraints: { page_code: /#{Settings.simple_pages.join('|')}/ }
    get '/countries/visa' => 'pages#visa_index', as: :visa_page
    get '/countries/visa/:id' => 'pages#visa_show', as: :visa_show_page
  end
  scope path: 'rest' do

    resources :beach_rest, only: [:index], path: 'beach' do
      get 'month/:month', to: :index, on: :collection, as: :by_month, constraints: {month: /[1-9]|1[0-2]/}
    end

    resources :excursion_tours, only: :index
    resources :river_cruises, only: [:show, :index] do
      resources :motor_ships, only: [:show]
    end
    resources :bus_tours, only: [:show, :index]
    resources :active_rest, only: [:show, :index]
    resources :rest_for_children, only: [:index]
    resources :language_camps, only: [:index]

    resources :school_bus_tours, only: [:show, :index]
    resources :school_train_tours, only: [:show, :index]
    resources :school_overseas_tours, only: [:show, :index]
    resources :sanatoria, only: [:show, :index]
    resources :camp_and_works, only: [:show, :index]
    resources :krasnodar_tours, only: [:index]

    resources :school_tour, only: [:index]
    resources :piligrim_tour, only: [:index]

  end

  resources :messages, only: [:new, :create]

  match "/weather_forecast" => 'application#weather_forecast', :constraints => { :only_ajax => true }

end

app/controllers/beach_rest_controller.rb
class BeachRestController < ApplicationController

  layout 'wide'
  add_breadcrumb path: :beach_rest_index_path

  def index
    @calendar = Calendar.new(params[:month])
    @beaches = Beach.grouped_by_month(@calendar.current_month)

    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

end

app/views/beach_rest/_beach_table.html.slim
#beach_table
  -if Beach.all
    div#months
      = csrf_meta_tags
      = link_to '<', by_month_beach_rest_index_path(@calendar.prev), title: 'Назад', remote: true, class: "btn"
      '
      = Calendar.month_name(@calendar.current_month)
      '
      = link_to '>', by_month_beach_rest_index_path(@calendar.next), title: 'Вперед', remote: true, class: "btn"
      hr
  - if @beaches.present?
    table.page-table
      col.pt-col-f
        tr
          th rowspan="2" Страна
          th colspan="3" Вылет возможен из
          th rowspan="2" Виза
          th rowspan="2" Температура воды
          th rowspan="2" Температура воздуха
        tr
          th Москва
          th Пермь
          th Уфа
        - @beaches[@calendar.current_month].each do |b|
          tr
            td.first-col= b.country.try(:name)
            - if data = b.country.try(:specify_airlines)
              - data.each do |a|
                td.airlines== airlines_links(a)
            td= b.country.try(:visa)
            td= b.t_air
            td= b.t_water

app/views/beach_rest/index.html.slim
- title @page.title
- meta_description @page.description
- meta_keywords @page.keywords

.page-block-wrap
  h2.page-header-u
    span= @page.name

  p.page-par
    = @page.content.html_safe

.page-block-wrap
  h2.page-header-u
    span Где отдохнуть

  = render 'beach_rest/beach_table'

app/views/beach_rest/index.js.erb
$("#beach_table").replaceWith("<%=j render partial: 'beach_table', object: @calendar, as: :calendar, object: @beaches, as: :beaches %>")