config/routes.rb
Tourrest::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root to: 'welcome#index'

  scope controller: :pages do
    get 'service/:page_code', to: :service_page,  as: :service_page, constraints: { page_code: /#{Settings.service_pages.join('|')}/ }
    get '/:page_code', to: :simple_page,  as: :simple_page, constraints: { page_code: /#{Settings.simple_pages.join('|')}/ }
    get '/countries/visa' => 'pages#visa_index', as: :visa_page
    get '/countries/visa/:id' => 'pages#visa_show', as: :visa_show_page
  end
  scope path: 'rest' do

    resources :beach_rest, only: [:index], path: 'beach' do
      get 'month/:month', to: :index, on: :collection, as: :by_month, constraints: {month: /[1-9]|1[0-2]/}
    end

    resources :excursion_tours, only: :index
    resources :river_cruises, only: [:show, :index] do
      resources :motor_ships, only: [:show]
    end
    resources :bus_tours, only: [:show, :index]
    resources :active_rest, only: [:show, :index]
    resources :rest_for_children, only: [:index]
    resources :language_camps, only: [:index]

    resources :school_bus_tours, only: [:show, :index]
    resources :school_train_tours, only: [:show, :index]
    resources :school_overseas_tours, only: [:show, :index]
    resources :sanatoria, only: [:show, :index]
    resources :camp_and_works, only: [:show, :index]
    resources :krasnodar_tours, only: [:index]

    resources :school_tour, only: [:index]
    resources :piligrim_tour, only: [:index]

  end

  resources :messages, only: [:new, :create]

  match "/weather_forecast" => 'application#weather_forecast', :constraints => { :only_ajax => true }

end

app/views/shared/_breadcrumbs.html.slim
.page-block-wrap
  ul.list-hr.page-crumbs
    li= link_to 'Главная', root_path
    - breadcrumbs.each do |b|
      li= b

app/views/shared/_flash.html.slim
- flash.each do |key, msg|
  div.flash id="#{key}"
    p= msg
  .clear-fix

app/views/shared/_footer.html.slim
.page-content-footer-push

.footer-wrap

  .m-grid-row.footer-row
    .m-grid-columns.width-1100.align-center.footer-columns-bg
      .m-grid-col.m-grid-col-right
        span.footer-copy-label.text-right.text-shadow &copy; Copyright Туризм и отдых #{Time.now.strftime('%Y')}
      .clear-fix

app/views/shared/_forecast.html.slim
#forecast.forecast
  - if @w_data
    .w-icon
      = image_tag(@w_data[:icon_path], alt: @w_data[:description])
    .w-params
      span#temp= "#{@w_data[:temp_min].floor} .. #{@w_data[:temp_max].floor} C."
      span#description
        | #{@w_data[:description]}
      span
        ' Ветер:
        span#wind #{I18n.t('wind_directions.' + @w_data[:wind_direction])} #{@w_data[:wind_speed]} м/с
      span#humidity
        ' Влажность:
        span #{@w_data[:humidity]}%
  - else
    .error Погодный сервис не доступен!
  .clear-fix

app/views/shared/_header.html.slim
.m-grid-row.header-row
  .m-grid-columns.width-1200.align-center.header-columns-bg
    .m-grid-col.m-grid-col-left.logo-col-w
      div#site-logo
        a href="#{root_path}" title="Туризм и отдых"
          span#sub.text-shadow турагентство
          span#main.text-shadow Туризм и Отдых

      ul.menu-hr.header-menu
        li
          = active_link_to 'Главная', root_path, active: :inclusive
        li
          = active_link_to 'О нас', simple_page_path('about_us'), active: :inclusive
        li
          = active_link_to 'Контакты', simple_page_path('contacts'), active: :inclusive
        li
          = active_link_to 'Электронная заявка', new_message_path, active: ['messages']
    .m-grid-col.m-grid-col-right.contacts-col-w
      .contacts-wrap
        span.contact-itm.cont-city г. Чайковский
        span.contact-itm.cont-street ул. К. Маркса, 26
        span.contact-itm.cont-phone= '(34241) 3-29-34'
    .clear-fix

app/views/shared/_menu.html.slim
.column-title-bg
  span Услуги

ul.list-vr.column-list-menu.space-bottom-25
  li
    - if page = Page.find_by_code(:visa)
      = active_link_to page.name, visa_page_path, active: :inclusive
  - Settings.service_pages.each do |p|
    li
      -if page = Page.find_by_code(p)
        = active_link_to page.name, service_page_path(p), active: :inclusive

app/views/shared/_news.html.slim
- if @slides.count > 0
  .column-title-bg
    span Новости
  .news-slides-container.space-bottom-25
    #news-slides
      .news-slides
        - @slides.each do |slide|
          div
            div#img
              = image_tag(slide.file.url, options = {alt: slide.title})
            div#description-bg.opacity
            div#description
              h3= slide.title
              -if slide.text
                = slide.text.html_safe


      .clear-fix

app/views/shared/_partners.html.slim
.m-grid-row.carousel-row
  .m-grid-columns.width-950.align-center
    .m-grid-col.m-grid-col-left
      .carousel-wrap

        .carousel-header.text-center
          span
            span Партнеры

        .carousel-container
          #partners-logos
            .carousel-item
              img src="/images/partners-logos/itm-11.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-3.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-4.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-5.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-6.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-7.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-8.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-9.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-10.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-1.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-12.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-13.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-14.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-15.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-16.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-17.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-18.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-19.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-20.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-21.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-22.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-23.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-24.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-25.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-26.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-27.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-28.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-29.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-30.png" alt=""
            .carousel-item
              img src="/images/partners-logos/itm-31.png" alt=""
          .clear-fix
          a class="carousel-item-prev" id="partners-logos-prev" href="#"
            span prev
          a class="carousel-item-next" id="partners-logos-next" href="#"
            span next

        .carousel-underline
    .clear-fix

app/views/shared/_rate_of_exchange.html.slim
.column-title
  span Курсы валют
table.currency-tbl
  col class="col-c-t"
  col class="col-c-v"
  tr
    td.currency-title
      span.usd Доллар США
    td.currency-value
      span #{@rates.nil? ?  '-' : @rates[:usd]} руб
  tr
    td class="currency-title"
      span.euro Евро
    td class="currency-value"
      span #{@rates.nil? ?  '-' : @rates[:eur]} руб
  tr
    td.currency-info colspan="2"
      span
        ' Дата:
        span #{@rates.nil? ?  '-' : @rates[:date]}
      br
      span
        ' Источник:
        span #{@rates.nil? ?  '-' : @rates[:source]}

app/views/shared/_weather.html.slim
.column-title
  span Прогноз погоды
div class="weather-inform"
  - if @w_data
    .place_date
      = form_tag(weather_forecast_path, remote: true, id: 'weather_forecast')
        = select_tag 'city_name', options_for_select(@w_cities, @current_city), {include_blank: false, class: "w-place", :onchange=>'$("#weather_forecast").submit();' }
        = select_tag 'date', options_for_select(@dates,@current_date), {include_blank: false, class: "w-date", :onchange=>'$("#weather_forecast").submit();'}
      .clear-fix
    = render :partial => 'shared/forecast'

app/views/shared/_widget.html.slim
.widget-wrap
  // http://vk.com/developers.php?oid=-1&p=Groups
  script type="text/javascript" src="//vk.com/js/api/openapi.js?87"></script>
  // VK Widget
  #vk_groups
    script type="text/javascript"
      | VK.Widgets.Group("vk_groups", {mode: 0, width: "235", height: "200"}, 16835376);